#!/usr/bin/env python3
"""
MSPB EA — ML Feedback Loop
===========================
Reads the ml_export_v2.csv (semicolon-delimited) produced by the EA,
trains an XGBoost classifier to predict P&L sign (win/loss), and
prints feature importances + suggested EA parameter tweaks.

Usage:
    python tools/ml_feedback.py --csv path/to/ml_export_v2.csv [--output suggestions.txt]
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import List, Dict, Any, Tuple


_MISSING_VALUES = {"", "nan", "null", "n/a", "na"}

def _parse_float(v: str) -> float:
    """Parse a float from CSV, treating common missing-value strings as 0.0."""
    return float(v) if v.lower() not in _MISSING_VALUES else 0.0
    "atr_pips",
    "adx_trend",
    "adx_entry",
    "spread_pips",
    "body_pips",
    "risk_mult",
]

TARGET_COL   = "pnl_gross"   # signed P&L; win if > 0
EVENT_FILTER = "ENTRY"       # only look at entry rows


def load_csv(path: str) -> List[Dict[str, str]]:
    rows = []
    with open(path, newline="", encoding="utf-8-sig") as fh:
        reader = csv.DictReader(fh, delimiter=";")
        for r in reader:
            rows.append(r)
    return rows


def build_dataset(rows: List[Dict[str, str]]) -> Tuple[List[List[float]], List[int], List[str]]:
    """Return X (features), y (0/1), feature_names."""
    X, y = [], []
    for r in rows:
        if r.get("event", "") not in ("ENTRY", "EXIT"):
            continue
        pnl_str = r.get(TARGET_COL, r.get("pnl", ""))
        try:
            pnl = float(pnl_str)
        except (ValueError, TypeError):
            continue
        label = 1 if pnl > 0 else 0

        feats = []
        for f in NUMERIC_FEATURES:
            v = r.get(f, "")
            try:
                feats.append(_parse_float(v))
            except ValueError:
                feats.append(0.0)
        X.append(feats)
        y.append(label)
    return X, y, NUMERIC_FEATURES


def train_xgboost(X, y) -> Any:
    try:
        import xgboost as xgb  # type: ignore
    except ImportError:
        print("xgboost not installed. Run: pip install xgboost", file=sys.stderr)
        sys.exit(1)

    model = xgb.XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        use_label_encoder=False,
        eval_metric="logloss",
        random_state=42,
    )
    model.fit(X, y)
    return model


def feature_importance_report(model, feature_names: List[str]) -> Dict[str, float]:
    import numpy as np  # type: ignore
    scores = model.feature_importances_
    ranking = sorted(zip(feature_names, scores), key=lambda t: t[1], reverse=True)
    print("\n=== Feature Importance (XGBoost gain) ===")
    for name, score in ranking:
        bar = "#" * int(score * 40)
        print(f"  {name:<20s} {score:.4f}  {bar}")
    return dict(ranking)


def suggest_params(importances: Dict[str, float]) -> Dict[str, str]:
    """Generate simple EA parameter suggestions based on top features."""
    suggestions: Dict[str, str] = {}
    top = sorted(importances, key=importances.get, reverse=True)[:3]  # type: ignore

    if "adx_trend" in top:
        suggestions["InpMinADXForEntry"] = "hint: raise threshold — ADX_trend is highly predictive"
    if "adx_entry" in top:
        suggestions["InpMinADXEntryFilter"] = "hint: raise threshold — ADX_entry is highly predictive"
    if "atr_pips" in top:
        suggestions["InpMinATR_Pips"] = "hint: raise floor — trades in low ATR regimes underperform"
    if "spread_pips" in top:
        suggestions["InpMaxSpreadPips_FX"] = "hint: lower max spread — spread strongly predicts loss"

    return suggestions


def write_output(path: str, importances: Dict[str, float], suggestions: Dict[str, str]) -> None:
    lines = ["# MSPB ML Feedback — generated by tools/ml_feedback.py\n\n"]
    lines.append("## Feature Importances\n")
    for k, v in sorted(importances.items(), key=lambda t: t[1], reverse=True):
        lines.append(f"{k}: {v:.4f}\n")
    lines.append("\n## Suggested EA Parameter Hints\n")
    for k, v in suggestions.items():
        lines.append(f"{k}: {v}\n")
    Path(path).write_text("".join(lines), encoding="utf-8")
    print(f"\nSuggestions written to {path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="MSPB ML Feedback Loop")
    parser.add_argument("--csv",    required=True, help="Path to ml_export_v2.csv")
    parser.add_argument("--output", default="ml_suggestions.txt",
                        help="Output file for suggestions (default: ml_suggestions.txt)")
    args = parser.parse_args()

    print(f"Loading {args.csv} …")
    rows = load_csv(args.csv)
    print(f"  {len(rows)} rows loaded")

    X, y, feat_names = build_dataset(rows)
    print(f"  {len(X)} labelled trade rows (win={sum(y)}, loss={len(y)-sum(y)})")

    if len(X) < 30:
        print("Not enough data (< 30 trades) for reliable ML. Keep trading and re-run later.")
        sys.exit(0)

    model = train_xgboost(X, y)
    importances = feature_importance_report(model, feat_names)
    suggestions  = suggest_params(importances)

    print("\n=== Suggested Parameter Hints ===")
    for k, v in suggestions.items():
        print(f"  {k}: {v}")

    write_output(args.output, importances, suggestions)


if __name__ == "__main__":
    main()
